export const tasks = [
  {
    id: 1,
    title: "Learning Java",
    description: "Finish java course and project.",
    timeToFinish: 0,
    dueDate: "2025-01-30",
    priority: 3,
    status: "standby",
    active: true,
    link: "https://www.google.com",
    // category: "learning",
    // attachment: "leite_receita.pdf",
  },
  {
    id: 2,
    title: "Read a book",
    description: "Read 30 pages of a book.",
    timeToFinish: 0,
    dueDate: "2025-01-20",
    priority: 1,
    status: "standby",
    active: false,
    link: "https://www.google.com",
  },
  {
    id: 3,
    title: "Write documentation",
    description: "Finish java project documentation.",
    timeToFinish: 0,
    dueDate: "2025-01-26",
    priority: 2,
    status: "done",
    active: false,
    link: "https://www.google.com",
  },
  {
    id: 4,
    title: "Code Review",
    description: "Review the pull requests for the new feature branch.",
    timeToFinish: 120,
    dueDate: "2025-01-15",
    priority: 1,
    status: "standby",
    active: false,
    link: "https://github.com",
  },
  {
    id: 5,
    title: "Prepare Presentation",
    description: "Create slides for the quarterly team meeting.",
    timeToFinish: 180,
    dueDate: "2025-01-20",
    priority: 2,
    status: "done",
    active: false,
    link: "https://www.slides.com",
  },
  {
    id: 6,
    title: "Update Dependencies",
    description: "Update project dependencies to their latest versions.",
    timeToFinish: 60,
    dueDate: "2025-01-18",
    priority: 3,
    status: "standby",
    active: false,
    link: "https://www.npmjs.com",
  },
  {
    id: 7,
    title: "Team Feedback Session",
    description: "Conduct a feedback session with the development team.",
    timeToFinish: 90,
    dueDate: "2025-01-22",
    priority: 1,
    status: "standby",
    active: false,
    link: "https://www.zoom.com",
  },
  {
    id: 8,
    title: "Bug Fixing",
    description: "Resolve critical issues reported in the latest build.",
    timeToFinish: 300,
    dueDate: "2025-01-25",
    priority: 1,
    status: "standby",
    active: false,
    link: "https://www.bugtracker.com",
  },
  {
    id: 9,
    title: "Research New Framework",
    description: "Evaluate the benefits of adopting a new frontend framework.",
    timeToFinish: 240,
    dueDate: "2025-01-30",
    priority: 3,
    status: "standby",
    active: false,
    link: "https://www.techdocs.com",
  },
];
